version: '3.8'  # Зазначте версію Docker Compose

services:
  db:
    image: postgres:latest
    container_name: app-db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 102712
    ports:
      - "5433:5432"  # змінив порт з 5432 на 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: ./django_project
      dockerfile: django_project/Dockerfile
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=102712
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./django_project:/app

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  postgres_data: